language: python
python:
    - "2.6"
    - "2.7"
# Command to install dependencies
install: 
    # OWTF dependencies
    - pip install lxml argparse jinja2 tornado pycurl
    # Test dependencies (nose is already installed in the Travis environment)
    - pip install flexmock pyhamcrest coverage nose-html nose-parameterized
# Command to run tests
script:
    - cd tests
    - ./run_tests.py --all --with-coverage
notifications:
    irc: "irc.freenode.net#owtf"